name: Deploy my_3d_landing_page

# Define when the workflow should run (on each push to the main branch).
on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to AWS
        uses: aws-actions/deploy-to-elastic-beanstalk@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my_3d_landing_page
          environment_name: My3dlandingpage-env
          region: us-west-2
          deployment_package: "C:\\source\\react\\my_3d_landing_page.zip"

